### ISSUE TITLE
hostname: Command not found.

### ISSUE THREAD

**Issue by erikohara** [corticometrics/fs6-cloud#4]
Running the command:

> docker run -it --rm \
  -e FS_KEY='****' \
  -v /path/to/subjects:/subjects \
  corticometrics/fs7-aws:latest \
  recon-all -s a-sub-001 -all -parallel

I'm getting:

> Subject Stamp: freesurfer-linux-centos7_x86_64-7.1.1-20200723-8b40551
Current Stamp: freesurfer-linux-centos7_x86_64-7.1.1-20200723-8b40551
INFO: SUBJECTS_DIR is /subjects
Actual FREESURFER_HOME /freesurfer
-rw-r--r-- 1 root root 85655 Nov  2 18:23 /subjects/a-sub-001/scripts/recon-all.log
Linux 4758a457a870 5.10.47-linuxkit #1 SMP Sat Jul 3 21:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
hostname: Command not found.

I entered the image, run `yum install -y hostname` and commited to a new image. 
This new image seems to be working.

**Comment by erikohara** [comment]
It worked with `corticometrics/fs7-aws:latest ` from AWS Batch.
Just locally in my Mac OS 10.14.6 that this problem occurs.

**Comment by pwighton** [comment]
Thanks for the report @erikohara!  That's strange there's a difference in behavior.  We can include `hostname` in the next version of the container.
